
override['filebeat']['group.name'] = "cs"
override['filebeat']['app.name'] = "css-be"
override['filebeat']['filebeat.prospector.config.map'] = '[
	{
		"paths": ["/var/tellme/css/logs/console.log"],
		"document_type": "cssbe-con-app"
		},
		{
		"paths": ["/var/tellme/css/logs/usagemetrics.log"],
		"document_type": "cssbe-user-metrics"
		},
		{
			"paths": ["/var/tellme/css/logs/user_auditlog.log"],
			"document_type": "cssbe-user-audit"
		}
]';

default['Self-Serve-BE']['JAVA'] = "java-11-openjdk.x86_64"
default['Self-Serve-BE']['CSS-APP-HOME'] = "/var/tellme/css"
default['Self-Serve-BE']['CSS-APP-BUILD-DIR'] = "#{node['Self-Serve-BE']['CSS-APP-HOME']}/build"
default['Self-Serve-BE']['CSS-APP-CONFIG-DIR'] = "#{node['Self-Serve-BE']['CSS-APP-HOME']}/conf"
default['Self-Serve-BE']['CSS-APP-LOGBACK-URL'] = "#{node['Self-Serve-BE']['CSS-APP-CONFIG-DIR']}/logback.xml"
default['Self-Serve-BE']['CSS-APP-CLEANUP-SCRIPT-URL'] = "#{node['Self-Serve-BE']['CSS-APP-CONFIG-DIR']}/css_be_log_cleanup.sh"
default['Self-Serve-BE']['CSS-APP-LOG-DIR'] = "#{node['Self-Serve-BE']['CSS-APP-HOME']}/logs"
default['Self-Serve-BE']['CSS-APP-LOG-ARCHIVE-DIR'] = "#{node['Self-Serve-BE']['CSS-APP-LOG-DIR']}/archived"
default['Self-Serve-BE']['CSS-APP-WAR'] = "css.jar"

default['Self-Serve-BE']['CONF-FILE']  = "/tools/config/current/statusd.conf"
default['Self-Serve-BE']['Self-Serve-BEJava']  = "/usr/local/statusd/libexec/check_process_css"
default['Self-Serve-BE']['Self-Serve-BE-CheckLOG']  = "/usr/local/statusd/libexec/check_css_log_expression"
default['Self-Serve-BE']['Self-Serve-BEhttp'] = "/usr/local/statusd/libexec/check_http_css"
default['Self-Serve-BE']['service_log'] = '/var/tellme/css/logs/application.log'
default['Self-Serve-BE']['service_log_critical_pattern'] = "\\\"debug_level\\\":\\\"ERROR\\\""
default['Self-Serve-BE']['service_log_warn_pattern'] = "\\\"debug_level\\\":\\\"WARN\\\""

default['Self-Serve-BE']['spring.jpa.properties.hibernate.cache.use_query_cache'] = "true"
default['Self-Serve-BE']['spring.jpa.properties.hibernate.cache.use_second_level_cache'] = "true"
default['Self-Serve-BE']['spring.jpa.properties.hibernate.cache.region.factory_class'] = "org.hibernate.cache.jcache.JCacheRegionFactory"
default['Self-Serve-BE']['spring.jpa.properties.javax.persistence.sharedCache.mode'] = "ENABLE_SELECTIVE"


case node.chef_environment

when 'CENTRAL-DEV'
	override['logstash']['hosts']= "stable-logstash.lb-priv.sv2.247-inc.net:5120"

	default['Self-Serve-BE']['WAR-REPO'] = "http://nexus.cicd.sv2.247-inc.net/nexus/repository/commit/com/tfsc/ilabs/self-service/promoted/self-service-promoted.jar"
	default['Self-Serve-BE']['spring.datasource.url'] = "jdbc:mysql://dev-client-prov01.db.shared.int.sv2.247-inc.net:3306/self_serve?useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false"
	default['Self-Serve-BE']['spring.datasource.username'] = "centraladmin"
	default['Self-Serve-BE']['spring.datasource.password'] = "central@247"
	default['Self-Serve-BE']['spring.datasource.driver-class-name']= "com.mysql.cj.jdbc.Driver"
	default['Self-Serve-BE']['spring.jpa.database-platform'] = "org.hibernate.dialect.MySQL5InnoDBDialect"
	default['Self-Serve-BE']['spring.jpa.show-sql'] = "false"
	default['Self-Serve-BE']['spring.jpa.hibernate.ddl-auto'] = "update"
	default['Self-Serve-BE']['server.servlet.application-display-name'] = "Self Service Application"
	default['Self-Serve-BE']['spring.application.name'] = "self-serve"
	default['Self-Serve-BE']['server.servlet.context-path'] = "/${spring.application.name}"
	default['Self-Serve-BE']['spring.jackson.serialization.write_dates_as_timestamp'] = "false"
	default['Self-Serve-BE']['server.port'] = "8090"
	
	default['Self-Serve-BE']['CSS-APP-OKTA-BASE-URL'] = "https://login.247ai.com"
	default['Self-Serve-BE']['CSS-APP-OKTA-AUTH-SERVICE-ID'] = "ausio6nhipTHfHFYj0h7"
    default['Self-Serve-BE']['CSS-APP-CLIENT-ID'] = "0oaine4w6blKLPDfX0h7"
    default['Self-Serve-BE']['CSS-APP-CLIENT-SECRET'] = "96djByvC_gU8C0HboZkVDggJSwHTn2qosuaRPV90"
    default['Self-Serve-BE']['CSS-APP-OKTA-CONNECTION-TIMEOUT'] = "1000"
	default['Self-Serve-BE']['CSS-APP-OKTA-CONNECTION-MULTIPLY'] = "1000"
	default['Self-Serve-BE']['CSS-APP-CONTENT-SERVER-BASE-URL'] = "dev-ude-content.app.shared.int.lb-priv.sv2.247-inc.net"
	default['Self-Serve-BE']['CSS-APP-CONTENT-SERVER-CSS-CONTENT-BASE-PATH'] = "v1/assist-console-ui/current"
	default['Self-Serve-BE']['CSS-APP-DOC-LINK'] = "https://stable.developer.sv2.247-inc.net/docportal/Content/"
	default['Self-Serve-BE']['CSS-APP-VCC-APP-URL'] = "https://stable-engage.247.ai"
	default['Self-Serve-BE']['CSS-APP-SUPPORT-LINK']="https://247inc.atlassian.net/secure/RapidBoard.jspa?rapidView=1178&projectKey=SRE"
	default['Self-Serve-BE']['CSS-APP-TOOL-ROOT']="/self-serve"
	default['Self-Serve-BE']['CSS-APP-TOOL-NAME']="ASSIST"
	default['Self-Serve-BE']['CSS-APP-TOOL-TYPE']="internal"
	default['Self-Serve-BE']['CSS-APP-TOOL-TITLE']="Assist"
	default['Self-Serve-BE']['CSS-APP-OKTA-ENABLED']="true"
	default['Self-Serve-BE']['CSS-APP-ENV']="dev"
	default['Self-Serve-BE']['CSS-APP-SERVICE-BASE-URL']="https://dev.api.sv2.247-inc.net/self-serve/api"
	default['Self-Serve-BE']['CSS-APP-PARENT-BASE-URL'] = "https://dev.developer.sv2.247-inc.net/home"
	default['Self-Serve-BE']['CSS-APP-COOKIES-SECURE-FLAG'] = "false"
	default['Self-Serve-BE']['CSS-APP-COOKIES-HTTPONLY-FLAG'] = "false"
    default['Self-Serve-BE']['CSS-APP-PROXY-ENABLE'] = "true"
    default['Self-Serve-BE']['CSS-APP-PROXY-HOST'] = "proxy-grp1.lb-priv.sv2.247-inc.net"
    default['Self-Serve-BE']['CSS-APP-PROXY-PORT'] = "3128"
    default['Self-Serve-BE']['CSS-APP-PROXY-PROTOCOL'] = "http"
    default['Self-Serve-BE']['CSS-APP-SSO-DISABLE'] = "false"
    default['Self-Serve-BE']['CSS-APP-THREAD-COUNT'] = "100"
    default['Self-Serve-BE']['CSS-APP-WORKFLOW-INSTANCE-TIMEOUT'] = "30"
	default['Self-Serve-BE']['CSS-APP-UMS-BASE-URL'] = "https://stable.developer.sv2.247-inc.net"
	default['Self-Serve-BE']['location']      = "sv2"
    default['Self-Serve-BE']['webserver']     = "probe.backside.sv2.tellme.com"
    default['Self-Serve-BE']['probeserver']   = "probe.backside.sv2.tellme.com"
    default['Self-Serve-BE']['release']       = "statusd-20171023T2140"
    default['Self-Serve-BE']['mail_host']     = "mail.backside.sv2.tellme.com"
    default['Self-Serve-BE']['ntp_server']    = "ntp01.backside.sv2.tellme.com"
	default['Self-Serve-BE']['BULK-STORAGE'] = "gcp"
	default['Self-Serve-BE']['GCP-PROJECT-ID'] = "dev-chat-ccc1"
	default['Self-Serve-BE']['GCP-BUCKET-NAME'] = "dev-chat"
	default['Self-Serve-BE']['CREDENTIALS-FILE-PATH'] = "/var/tellme/css/conf/.gcp.json"

when 'CENTRAL-QA'

	override['logstash']['hosts']= "stable-logstash.lb-priv.sv2.247-inc.net:5120"

	default['Self-Serve-BE']['WAR-REPO'] = "http://nexus.cicd.sv2.247-inc.net/nexus/repository/qa/com/tfsc/ilabs/self-service/promoted/self-service-promoted.jar"
	default['Self-Serve-BE']['spring.datasource.url'] = "jdbc:mysql://qa-client-prov01.db.shared.int.sv2.247-inc.net:3306/self_serve?useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false"
	default['Self-Serve-BE']['spring.datasource.username'] = "centraladmin"
	default['Self-Serve-BE']['spring.datasource.password'] = "central@247"
	default['Self-Serve-BE']['spring.datasource.driver-class-name']= "com.mysql.cj.jdbc.Driver"
	default['Self-Serve-BE']['spring.jpa.database-platform'] = "org.hibernate.dialect.MySQL5InnoDBDialect"
	default['Self-Serve-BE']['spring.jpa.show-sql'] = "false"
	default['Self-Serve-BE']['spring.jpa.hibernate.ddl-auto'] = "update"
	default['Self-Serve-BE']['server.servlet.application-display-name'] = "Self Service Application"
	default['Self-Serve-BE']['spring.application.name'] = "self-serve"
	default['Self-Serve-BE']['server.servlet.context-path'] = "/${spring.application.name}"
	default['Self-Serve-BE']['spring.jackson.serialization.write_dates_as_timestamp'] = "false"
	default['Self-Serve-BE']['server.port'] = "8090"
	
	default['Self-Serve-BE']['CSS-APP-OKTA-BASE-URL'] = "https://login.247ai.com"
	default['Self-Serve-BE']['CSS-APP-OKTA-AUTH-SERVICE-ID'] = "ausio6nhipTHfHFYj0h7"
	default['Self-Serve-BE']['CSS-APP-CLIENT-ID'] = "0oaine4w6blKLPDfX0h7"
	default['Self-Serve-BE']['CSS-APP-CLIENT-SECRET'] = "96djByvC_gU8C0HboZkVDggJSwHTn2qosuaRPV90"
	default['Self-Serve-BE']['CSS-APP-OKTA-CONNECTION-TIMEOUT'] = "1000"
	default['Self-Serve-BE']['CSS-APP-OKTA-CONNECTION-MULTIPLY'] = "1000"
	
	default['Self-Serve-BE']['CSS-APP-CONTENT-SERVER-BASE-URL'] = "qa-ude-content.app.shared.int.lb-priv.sv2.247-inc.net"
	default['Self-Serve-BE']['CSS-APP-CONTENT-SERVER-CSS-CONTENT-BASE-PATH'] = "v1/assist-console-ui/environments/qa/statics/current/assist-console-ui"
	default['Self-Serve-BE']['CSS-APP-DOC-LINK'] = "https://stable.developer.sv2.247-inc.net/docportal/Content/"
	default['Self-Serve-BE']['CSS-APP-VCC-APP-URL'] = "https://stable-engage.247.ai"
	default['Self-Serve-BE']['CSS-APP-SUPPORT-LINK']="https://247inc.atlassian.net/secure/RapidBoard.jspa?rapidView=1178&projectKey=SRE"
	default['Self-Serve-BE']['CSS-APP-TOOL-ROOT']="/self-serve"
	default['Self-Serve-BE']['CSS-APP-TOOL-NAME']="ASSIST"
	default['Self-Serve-BE']['CSS-APP-TOOL-TYPE']="internal"
	default['Self-Serve-BE']['CSS-APP-TOOL-TITLE']="Assist"
	default['Self-Serve-BE']['CSS-APP-OKTA-ENABLED']="true"
	default['Self-Serve-BE']['CSS-APP-ENV']="qa"
	default['Self-Serve-BE']['CSS-APP-SERVICE-BASE-URL']="https://qa.api.sv2.247-inc.net/self-serve/api"
	default['Self-Serve-BE']['CSS-APP-PARENT-BASE-URL'] = "https://qa.developer.sv2.247-inc.net/home"
	default['Self-Serve-BE']['CSS-APP-COOKIES-SECURE-FLAG'] = "false"
	default['Self-Serve-BE']['CSS-APP-COOKIES-HTTPONLY-FLAG'] = "false"
	default['Self-Serve-BE']['CSS-APP-PROXY-ENABLE'] = "true"
	default['Self-Serve-BE']['CSS-APP-PROXY-HOST'] = "proxy-grp1.lb-priv.sv2.247-inc.net"
	default['Self-Serve-BE']['CSS-APP-PROXY-PORT'] = "3128"
	default['Self-Serve-BE']['CSS-APP-PROXY-PROTOCOL'] = "http"
	default['Self-Serve-BE']['CSS-APP-SSO-DISABLE'] = "true"
	default['Self-Serve-BE']['CSS-APP-THREAD-COUNT'] = "100"
	default['Self-Serve-BE']['CSS-APP-WORKFLOW-INSTANCE-TIMEOUT'] = "30"
	default['Self-Serve-BE']['CSS-APP-UMS-BASE-URL'] = "https://stable.developer.sv2.247-inc.net"
	default['Self-Serve-BE']['location']      = "sv2"
	default['Self-Serve-BE']['webserver']     = "probe.backside.sv2.tellme.com"
	default['Self-Serve-BE']['probeserver']   = "probe.backside.sv2.tellme.com"
	default['Self-Serve-BE']['release']       = "statusd-20171023T2140"
	default['Self-Serve-BE']['mail_host']     = "mail.backside.sv2.tellme.com"
	default['Self-Serve-BE']['ntp_server']    = "ntp01.backside.sv2.tellme.com"
	default['Self-Serve-BE']['BULK-STORAGE'] = "gcp"
	default['Self-Serve-BE']['GCP-PROJECT-ID'] = "dev-chat-ccc1"
	default['Self-Serve-BE']['GCP-BUCKET-NAME'] = "dev-chat"
	default['Self-Serve-BE']['CREDENTIALS-FILE-PATH'] = "/var/tellme/css/conf/.gcp.json"

when 'CENTRAL-PSR'

	override['logstash']['hosts']= "stable-logstash.lb-priv.sv2.247-inc.net:5120"

	default['Self-Serve-BE']['WAR-REPO'] = "http://nexus.cicd.sv2.247-inc.net/nexus/repository/psr/com/tfsc/ilabs/self-service/promoted/self-service-promoted.jar"
	default['Self-Serve-BE']['spring.datasource.url'] = "jdbc:mysql://psr-client-prov01.db.shared.int.sv2.247-inc.net:3306/self_serve?useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false"
	default['Self-Serve-BE']['spring.datasource.username'] = "centraladmin"
	default['Self-Serve-BE']['spring.datasource.password'] = "central@247"
	default['Self-Serve-BE']['spring.datasource.driver-class-name']= "com.mysql.cj.jdbc.Driver"
	default['Self-Serve-BE']['spring.jpa.database-platform'] = "org.hibernate.dialect.MySQL5InnoDBDialect"
	default['Self-Serve-BE']['spring.jpa.show-sql'] = "false"
	default['Self-Serve-BE']['spring.jpa.hibernate.ddl-auto'] = "update"
	default['Self-Serve-BE']['server.servlet.application-display-name'] = "Self Service Application"
	default['Self-Serve-BE']['spring.application.name'] = "self-serve"
	default['Self-Serve-BE']['server.servlet.context-path'] = "/${spring.application.name}"
	default['Self-Serve-BE']['spring.jackson.serialization.write_dates_as_timestamp'] = "false"
	default['Self-Serve-BE']['server.port'] = "8090"
	
	default['Self-Serve-BE']['CSS-APP-OKTA-BASE-URL'] = "https://login.247ai.com"
	default['Self-Serve-BE']['CSS-APP-OKTA-AUTH-SERVICE-ID'] = "ausio6nhipTHfHFYj0h7"
	default['Self-Serve-BE']['CSS-APP-CLIENT-ID'] = "0oaine4w6blKLPDfX0h7"
	default['Self-Serve-BE']['CSS-APP-CLIENT-SECRET'] = "96djByvC_gU8C0HboZkVDggJSwHTn2qosuaRPV90"
	default['Self-Serve-BE']['CSS-APP-OKTA-CONNECTION-TIMEOUT'] = "1000"
	default['Self-Serve-BE']['CSS-APP-OKTA-CONNECTION-MULTIPLY'] = "1000"
	
	default['Self-Serve-BE']['CSS-APP-CONTENT-SERVER-BASE-URL'] = "psr-ude-content.app.shared.int.lb-priv.sv2.247-inc.net"
	default['Self-Serve-BE']['CSS-APP-CONTENT-SERVER-CSS-CONTENT-BASE-PATH'] = "v1/assist-console-ui/environments/psr/statics/current/assist-console-ui"
	default['Self-Serve-BE']['CSS-APP-DOC-LINK'] = "https://stable.developer.sv2.247-inc.net/docportal/Content/"
	default['Self-Serve-BE']['CSS-APP-VCC-APP-URL'] = "https://stable-engage.247.ai"
	default['Self-Serve-BE']['CSS-APP-SUPPORT-LINK']="https://247inc.atlassian.net/secure/RapidBoard.jspa?rapidView=1178&projectKey=SRE"
	default['Self-Serve-BE']['CSS-APP-TOOL-ROOT']="/self-serve"
	default['Self-Serve-BE']['CSS-APP-TOOL-NAME']="ASSIST"
	default['Self-Serve-BE']['CSS-APP-TOOL-TYPE']="internal"
	default['Self-Serve-BE']['CSS-APP-TOOL-TITLE']="Assist"
	default['Self-Serve-BE']['CSS-APP-OKTA-ENABLED']="true"
	default['Self-Serve-BE']['CSS-APP-ENV']="psr"
	default['Self-Serve-BE']['CSS-APP-SERVICE-BASE-URL']="https://psr.api.sv2.247-inc.net/self-serve/api"
	default['Self-Serve-BE']['CSS-APP-PARENT-BASE-URL'] = "https://psr.developer.sv2.247-inc.net/home"
	default['Self-Serve-BE']['CSS-APP-COOKIES-SECURE-FLAG'] = "false"
	default['Self-Serve-BE']['CSS-APP-COOKIES-HTTPONLY-FLAG'] = "false"

	default['Self-Serve-BE']['CSS-APP-PROXY-ENABLE'] = "true"
	default['Self-Serve-BE']['CSS-APP-PROXY-HOST'] = "proxy-grp1.lb-priv.sv2.247-inc.net"
	default['Self-Serve-BE']['CSS-APP-PROXY-PORT'] = "3128"
	default['Self-Serve-BE']['CSS-APP-PROXY-PROTOCOL'] = "http"
	default['Self-Serve-BE']['CSS-APP-SSO-DISABLE'] = "false"
	default['Self-Serve-BE']['CSS-APP-THREAD-COUNT'] = "100"
	default['Self-Serve-BE']['CSS-APP-WORKFLOW-INSTANCE-TIMEOUT'] = "30"
	default['Self-Serve-BE']['CSS-APP-UMS-BASE-URL'] = "https://stable.developer.sv2.247-inc.net"
	default['Self-Serve-BE']['location']      = "sv2"
	default['Self-Serve-BE']['webserver']     = "probe.backside.sv2.tellme.com"
	default['Self-Serve-BE']['probeserver']   = "probe.backside.sv2.tellme.com"
	default['Self-Serve-BE']['release']       = "statusd-20171023T2140"
	default['Self-Serve-BE']['mail_host']     = "mail.backside.sv2.tellme.com"
	default['Self-Serve-BE']['ntp_server']    = "ntp01.backside.sv2.tellme.com"
	default['Self-Serve-BE']['BULK-STORAGE'] = "gcp"
	default['Self-Serve-BE']['GCP-PROJECT-ID'] = "dev-chat-ccc1"
	default['Self-Serve-BE']['GCP-BUCKET-NAME'] = "dev-chat"
	default['Self-Serve-BE']['CREDENTIALS-FILE-PATH'] = "/var/tellme/css/conf/.gcp.json"

when 'CENTRAL-STABLE'
	
	override['logstash']['hosts']= "stable-logstash.lb-priv.sv2.247-inc.net:5120"

	default['Self-Serve-BE']['WAR-REPO'] = "http://nexus.cicd.sv2.247-inc.net/nexus/repository/stable-env/com/tfsc/ilabs/self-service/promoted/self-service-promoted.jar"
	default['Self-Serve-BE']['spring.datasource.url'] = "jdbc:mysql://stable-client-prov01.db.shared.int.sv2.247-inc.net:3306/self_serve?useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false"
	default['Self-Serve-BE']['spring.datasource.username'] = "centraladmin"
	default['Self-Serve-BE']['spring.datasource.password'] = "central@247"
	default['Self-Serve-BE']['spring.datasource.driver-class-name']= "com.mysql.cj.jdbc.Driver"
	default['Self-Serve-BE']['spring.jpa.database-platform'] = "org.hibernate.dialect.MySQL5InnoDBDialect"
	default['Self-Serve-BE']['spring.jpa.show-sql'] = "false"
	default['Self-Serve-BE']['spring.jpa.hibernate.ddl-auto'] = "update"
	default['Self-Serve-BE']['server.servlet.application-display-name'] = "Self Service Application"
	default['Self-Serve-BE']['spring.application.name'] = "self-serve"
	default['Self-Serve-BE']['server.servlet.context-path'] = "/${spring.application.name}"
	default['Self-Serve-BE']['spring.jackson.serialization.write_dates_as_timestamp'] = "false"
	default['Self-Serve-BE']['server.port'] = "8090"
	
	default['Self-Serve-BE']['CSS-APP-OKTA-BASE-URL'] = "https://login.247ai.com"
	default['Self-Serve-BE']['CSS-APP-OKTA-AUTH-SERVICE-ID'] = "ausio6nhipTHfHFYj0h7"
	default['Self-Serve-BE']['CSS-APP-CLIENT-ID'] = "0oaine4w6blKLPDfX0h7"
	default['Self-Serve-BE']['CSS-APP-CLIENT-SECRET'] = "96djByvC_gU8C0HboZkVDggJSwHTn2qosuaRPV90"
	default['Self-Serve-BE']['CSS-APP-OKTA-CONNECTION-TIMEOUT'] = "1000"
	default['Self-Serve-BE']['CSS-APP-OKTA-CONNECTION-MULTIPLY'] = "1000"

	default['Self-Serve-BE']['CSS-APP-CONTENT-SERVER-BASE-URL'] = "http://stable-engage.247.ai/"
	default['Self-Serve-BE']['CSS-APP-CONTENT-SERVER-CSS-CONTENT-BASE-PATH'] = "assist-console-ui/"
	default['Self-Serve-BE']['CSS-APP-DOC-LINK'] = "https://stable.developer.sv2.247-inc.net/docportal/Content/"
	default['Self-Serve-BE']['CSS-APP-VCC-APP-URL'] = "https://stable-engage.247.ai"
	default['Self-Serve-BE']['CSS-APP-SUPPORT-LINK']="https://247inc.atlassian.net/secure/RapidBoard.jspa?rapidView=1178&projectKey=SRE"
	default['Self-Serve-BE']['CSS-APP-TOOL-ROOT']="/self-serve"
	default['Self-Serve-BE']['CSS-APP-TOOL-NAME']="ASSIST"
	default['Self-Serve-BE']['CSS-APP-TOOL-TYPE']="internal"
	default['Self-Serve-BE']['CSS-APP-TOOL-TITLE']="Assist"
	default['Self-Serve-BE']['CSS-APP-OKTA-ENABLED']="true"
	default['Self-Serve-BE']['CSS-APP-ENV']="stable"
	default['Self-Serve-BE']['CSS-APP-SERVICE-BASE-URL']="http://stable-engage.247.ai/self-serve"
	default['Self-Serve-BE']['CSS-APP-PARENT-BASE-URL'] = "https://stable.developer.sv2.247-inc.net/home"
	
	default['Self-Serve-BE']['CSS-APP-COOKIES-SECURE-FLAG'] = "false"
	default['Self-Serve-BE']['CSS-APP-COOKIES-HTTPONLY-FLAG'] = "false"

	default['Self-Serve-BE']['CSS-APP-PROXY-ENABLE'] = "true"
	default['Self-Serve-BE']['CSS-APP-PROXY-HOST'] = "proxy-grp1.lb-priv.sv2.247-inc.net"
	default['Self-Serve-BE']['CSS-APP-PROXY-PORT'] = "3128"
	default['Self-Serve-BE']['CSS-APP-PROXY-PROTOCOL'] = "http"
	default['Self-Serve-BE']['CSS-APP-SSO-DISABLE'] = "false"
	default['Self-Serve-BE']['CSS-APP-THREAD-COUNT'] = "100"
	default['Self-Serve-BE']['CSS-APP-WORKFLOW-INSTANCE-TIMEOUT'] = "30"
	default['Self-Serve-BE']['CSS-APP-UMS-BASE-URL'] = "https://stable.developer.sv2.247-inc.net"
	default['Self-Serve-BE']['location']      = "sv2"
	default['Self-Serve-BE']['webserver']     = "probe.backside.sv2.tellme.com"
	default['Self-Serve-BE']['probeserver']   = "probe.backside.sv2.tellme.com"
	default['Self-Serve-BE']['release']       = "statusd-20171023T2140"
	default['Self-Serve-BE']['mail_host']     = "mail.backside.sv2.tellme.com"
	default['Self-Serve-BE']['ntp_server']    = "ntp01.backside.sv2.tellme.com"
	default['Self-Serve-BE']['BULK-STORAGE'] = "gcp"
	default['Self-Serve-BE']['GCP-PROJECT-ID'] = "dev-chat-ccc1"
	default['Self-Serve-BE']['GCP-BUCKET-NAME'] = "dev-chat"
	default['Self-Serve-BE']['CREDENTIALS-FILE-PATH'] = "/var/tellme/css/conf/.gcp.json"

when 'CENTRAL-SV1-STAGE'

	override['logstash']['hosts']= "logstash.logpool.lb-priv.sv1.247-inc.net:5120"

	default['Self-Serve-BE']['WAR-REPO'] = "http://nexus.cicd.sv2.247-inc.net/nexus/repository/stage/com/tfsc/ilabs/self-service/promoted/self-service-promoted.jar"
	default['Self-Serve-BE']['spring.datasource.url'] = "jdbc:mysql://client-prov.db.stg.lb-priv.sv1.247-inc.net:3306/self_serve?useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false"
	default['Self-Serve-BE']['spring.datasource.username'] = "centraladmin"
	default['Self-Serve-BE']['spring.datasource.password'] = "central@247"
	default['Self-Serve-BE']['spring.datasource.driver-class-name']= "com.mysql.cj.jdbc.Driver"
	default['Self-Serve-BE']['spring.jpa.database-platform'] = "org.hibernate.dialect.MySQL5InnoDBDialect"
	default['Self-Serve-BE']['spring.jpa.show-sql'] = "false"
	default['Self-Serve-BE']['spring.jpa.hibernate.ddl-auto'] = "update"
	default['Self-Serve-BE']['server.servlet.application-display-name'] = "Self Service Application"
	default['Self-Serve-BE']['spring.application.name'] = "self-serve"
	default['Self-Serve-BE']['server.servlet.context-path'] = "/${spring.application.name}"
	default['Self-Serve-BE']['spring.jackson.serialization.write_dates_as_timestamp'] = "false"
	default['Self-Serve-BE']['server.port'] = "8090"

	default['Self-Serve-BE']['CSS-APP-OKTA-BASE-URL'] = "https://login.247.ai/"
	default['Self-Serve-BE']['CSS-APP-OKTA-AUTH-SERVICE-ID'] = "aus70mcr3rrgyTW3e2p7"
	default['Self-Serve-BE']['CSS-APP-CLIENT-ID'] = "0oa3fky9wv0Wy5acb2p7"
	default['Self-Serve-BE']['CSS-APP-CLIENT-SECRET'] = "Ks1vpMP8PKErREeRFRrlt_8sEyvkrAXishojiWEV"
	default['Self-Serve-BE']['CSS-APP-OKTA-CONNECTION-TIMEOUT'] = "1000"
	default['Self-Serve-BE']['CSS-APP-OKTA-CONNECTION-MULTIPLY'] = "1000"

	default['Self-Serve-BE']['CSS-APP-CONTENT-SERVER-BASE-URL'] = "https://staging.developer.247-inc.net/"
	default['Self-Serve-BE']['CSS-APP-CONTENT-SERVER-CSS-CONTENT-BASE-PATH'] = "assist-console-ui/"
	default['Self-Serve-BE']['CSS-APP-DOC-LINK'] = "https://staging.api.247-inc.net/docportal/Content/"
	default['Self-Serve-BE']['CSS-APP-VCC-APP-URL'] = "https://vcc-stage.cac.247-inc.net"
	default['Self-Serve-BE']['CSS-APP-SUPPORT-LINK']="https://247inc.atlassian.net/secure/RapidBoard.jspa?rapidView=1178&projectKey=SRE"
	default['Self-Serve-BE']['CSS-APP-TOOL-ROOT']="/self-serve"
	default['Self-Serve-BE']['CSS-APP-TOOL-NAME']="ASSIST"
	default['Self-Serve-BE']['CSS-APP-TOOL-TYPE']="internal"
	default['Self-Serve-BE']['CSS-APP-TOOL-TITLE']="Assist"
	default['Self-Serve-BE']['CSS-APP-OKTA-ENABLED']="true"
	default['Self-Serve-BE']['CSS-APP-ENV']="staging"
	default['Self-Serve-BE']['CSS-APP-SERVICE-BASE-URL']="https://staging.developer.247-inc.net/self-serve"
	default['Self-Serve-BE']['CSS-APP-PARENT-BASE-URL'] = "https://staging.developer.247-inc.net/home"
	default['Self-Serve-BE']['CSS-APP-COOKIES-SECURE-FLAG'] = "true"
	default['Self-Serve-BE']['CSS-APP-COOKIES-HTTPONLY-FLAG'] = "true"
	default['Self-Serve-BE']['CSS-APP-PROXY-ENABLE'] = "true"
	default['Self-Serve-BE']['CSS-APP-PROXY-HOST'] = "proxy-grp1.lb-priv.sv1.247-inc.net"
	default['Self-Serve-BE']['CSS-APP-PROXY-PORT'] = "3128"
	default['Self-Serve-BE']['CSS-APP-PROXY-PROTOCOL'] = "http"
	default['Self-Serve-BE']['CSS-APP-SSO-DISABLE'] = "false"
	default['Self-Serve-BE']['CSS-APP-THREAD-COUNT'] = "100"
	default['Self-Serve-BE']['CSS-APP-WORKFLOW-INSTANCE-TIMEOUT'] = "30"
	default['Self-Serve-BE']['CSS-APP-UMS-BASE-URL'] = "https://internal-staging.api.247-inc.net"
	default['Self-Serve-BE']['location']      = "sv1"
	default['Self-Serve-BE']['webserver']     = "probe.private.sv1.tellme.com"
	default['Self-Serve-BE']['probeserver']   = "probe.private.sv1.tellme.com"
	default['Self-Serve-BE']['release']       = "statusd-20171023T2140"
	default['Self-Serve-BE']['mail_host']     = "mail.private.sv1.tellme.com"
	default['Self-Serve-BE']['ntp_server']    = "ntp01.private.sv1.tellme.com"
	default['Self-Serve-BE']['BULK-STORAGE'] = "gcp"
	default['Self-Serve-BE']['GCP-PROJECT-ID'] = "stg-chat-2a60"
	default['Self-Serve-BE']['GCP-BUCKET-NAME'] = "stg-chat"
	default['Self-Serve-BE']['CREDENTIALS-FILE-PATH'] = "/var/tellme/css/conf/.gcp.json"

when 'CENTRAL-VA1-STAGE'
	
	override['logstash']['hosts']= "logstash.logpool.lb-priv.va1.247-inc.net:5120"

	default['Self-Serve-BE']['WAR-REPO'] = "http://nexus.cicd.sv2.247-inc.net/nexus/repository/stage/com/tfsc/ilabs/self-service/promoted/self-service-promoted.jar"
	default['Self-Serve-BE']['spring.datasource.url'] = "jdbc:mysql://client-prov.db.stg.lb-priv.va1.247-inc.net:3306/self_serve?useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false"
	default['Self-Serve-BE']['spring.datasource.username'] = "centraladmin"
	default['Self-Serve-BE']['spring.datasource.password'] = "central@247"
	default['Self-Serve-BE']['spring.datasource.driver-class-name']= "com.mysql.cj.jdbc.Driver"
	default['Self-Serve-BE']['spring.jpa.database-platform'] = "org.hibernate.dialect.MySQL5InnoDBDialect"
	default['Self-Serve-BE']['spring.jpa.show-sql'] = "false"
	default['Self-Serve-BE']['spring.jpa.hibernate.ddl-auto'] = "update"
	default['Self-Serve-BE']['server.servlet.application-display-name'] = "Self Service Application"
	default['Self-Serve-BE']['spring.application.name'] = "self-serve"
	default['Self-Serve-BE']['server.servlet.context-path'] = "/${spring.application.name}"
	default['Self-Serve-BE']['spring.jackson.serialization.write_dates_as_timestamp'] = "false"
	default['Self-Serve-BE']['server.port'] = "8090"

	default['Self-Serve-BE']['CSS-APP-OKTA-BASE-URL'] = "https://login.247.ai/"
	default['Self-Serve-BE']['CSS-APP-OKTA-AUTH-SERVICE-ID'] = "aus70mcr3rrgyTW3e2p7"
	default['Self-Serve-BE']['CSS-APP-CLIENT-ID'] = "0oa3fky9wv0Wy5acb2p7"
	default['Self-Serve-BE']['CSS-APP-CLIENT-SECRET'] = "Ks1vpMP8PKErREeRFRrlt_8sEyvkrAXishojiWEV"
	default['Self-Serve-BE']['CSS-APP-OKTA-CONNECTION-TIMEOUT'] = "1000"
	default['Self-Serve-BE']['CSS-APP-OKTA-CONNECTION-MULTIPLY'] = "1000"

	default['Self-Serve-BE']['CSS-APP-CONTENT-SERVER-BASE-URL'] = "https://staging.developer.247-inc.net/"
	default['Self-Serve-BE']['CSS-APP-CONTENT-SERVER-CSS-CONTENT-BASE-PATH'] = "assist-console-ui/"
	default['Self-Serve-BE']['CSS-APP-DOC-LINK'] = "https://staging.api.247-inc.net/docportal/Content/"
	default['Self-Serve-BE']['CSS-APP-VCC-APP-URL'] = "https://vcc-stage.cac.247-inc.net"
	default['Self-Serve-BE']['CSS-APP-SUPPORT-LINK']="https://247inc.atlassian.net/secure/RapidBoard.jspa?rapidView=1178&projectKey=SRE"
	default['Self-Serve-BE']['CSS-APP-TOOL-ROOT']="/self-serve"
	default['Self-Serve-BE']['CSS-APP-TOOL-NAME']="ASSIST"
	default['Self-Serve-BE']['CSS-APP-TOOL-TYPE']="internal"
	default['Self-Serve-BE']['CSS-APP-TOOL-TITLE']="Assist"
	default['Self-Serve-BE']['CSS-APP-OKTA-ENABLED']="true"
	default['Self-Serve-BE']['CSS-APP-ENV']="staging"
	default['Self-Serve-BE']['CSS-APP-SERVICE-BASE-URL']="https://staging.developer.247-inc.net/self-serve"
	default['Self-Serve-BE']['CSS-APP-PARENT-BASE-URL'] = "https://staging.developer.247-inc.net/home"

	default['Self-Serve-BE']['CSS-APP-COOKIES-SECURE-FLAG'] = "true"
	default['Self-Serve-BE']['CSS-APP-COOKIES-HTTPONLY-FLAG'] = "true"
	default['Self-Serve-BE']['CSS-APP-PROXY-ENABLE'] = "true"
	default['Self-Serve-BE']['CSS-APP-PROXY-HOST'] = "proxy-grp1.lb-priv.va1.247-inc.net"
	default['Self-Serve-BE']['CSS-APP-PROXY-PORT'] = "3128"
	default['Self-Serve-BE']['CSS-APP-PROXY-PROTOCOL'] = "http"
	default['Self-Serve-BE']['CSS-APP-SSO-DISABLE'] = "false"
	default['Self-Serve-BE']['CSS-APP-THREAD-COUNT'] = "100"
	default['Self-Serve-BE']['CSS-APP-WORKFLOW-INSTANCE-TIMEOUT'] = "30"
	default['Self-Serve-BE']['CSS-APP-UMS-BASE-URL'] = "https://internal-staging.api.247-inc.net"
	default['Self-Serve-BE']['location']      = "va1"
	default['Self-Serve-BE']['webserver']     = "probe.private.va1.tellme.com"
	default['Self-Serve-BE']['probeserver']   = "probe.private.va1.tellme.com"
	default['Self-Serve-BE']['release']       = "statusd-20171023T2140"
	default['Self-Serve-BE']['mail_host']     = "mail.private.va1.tellme.com"
	default['Self-Serve-BE']['ntp_server']    = "ntp01.private.va1.tellme.com"
	default['Self-Serve-BE']['BULK-STORAGE'] = "gcp"
	default['Self-Serve-BE']['GCP-PROJECT-ID'] = "stg-chat-2a60"
	default['Self-Serve-BE']['GCP-BUCKET-NAME'] = "stg-chat"
	default['Self-Serve-BE']['CREDENTIALS-FILE-PATH'] = "/var/tellme/css/conf/.gcp.json"

when 'CENTRAL-SV1-PROD'
	
	override['logstash']['hosts']= "logstash.logpool.lb-priv.sv1.247-inc.net:5120"

	default['Self-Serve-BE']['WAR-REPO'] = "http://nexus.cicd.sv2.247-inc.net/nexus/repository/prod/com/tfsc/ilabs/self-service/promoted/self-service-promoted.jar"
	default['Self-Serve-BE']['spring.datasource.url'] = "jdbc:mysql://client-prov.db.lb-priv.sv1.247-inc.net:3306/self_serve?useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false"
	default['Self-Serve-BE']['spring.datasource.username'] = "centraladmin"
	default['Self-Serve-BE']['spring.datasource.password'] = "central@247"
	default['Self-Serve-BE']['spring.datasource.driver-class-name']= "com.mysql.cj.jdbc.Driver"
	default['Self-Serve-BE']['spring.jpa.database-platform'] = "org.hibernate.dialect.MySQL5InnoDBDialect"
	default['Self-Serve-BE']['spring.jpa.show-sql'] = "false"
	default['Self-Serve-BE']['spring.jpa.hibernate.ddl-auto'] = "update"
	default['Self-Serve-BE']['server.servlet.application-display-name'] = "Self Service Application"
	default['Self-Serve-BE']['spring.application.name'] = "self-serve"
	default['Self-Serve-BE']['server.servlet.context-path'] = "/${spring.application.name}"
	default['Self-Serve-BE']['spring.jackson.serialization.write_dates_as_timestamp'] = "false"
	default['Self-Serve-BE']['server.port'] = "8090"

	default['Self-Serve-BE']['CSS-APP-OKTA-BASE-URL'] = "https://login.247.ai/"
	default['Self-Serve-BE']['CSS-APP-OKTA-AUTH-SERVICE-ID'] = "aus70mcr3rrgyTW3e2p7"
	default['Self-Serve-BE']['CSS-APP-CLIENT-ID'] = "0oa3fky9wv0Wy5acb2p7"
	default['Self-Serve-BE']['CSS-APP-CLIENT-SECRET'] = "Ks1vpMP8PKErREeRFRrlt_8sEyvkrAXishojiWEV"
	default['Self-Serve-BE']['CSS-APP-OKTA-CONNECTION-TIMEOUT'] = "1000"
	default['Self-Serve-BE']['CSS-APP-OKTA-CONNECTION-MULTIPLY'] = "1000"

	default['Self-Serve-BE']['CSS-APP-CONTENT-SERVER-BASE-URL'] = "https://engage.247.ai/"
	default['Self-Serve-BE']['CSS-APP-CONTENT-SERVER-CSS-CONTENT-BASE-PATH'] = "assist-console-ui/"
	default['Self-Serve-BE']['CSS-APP-DOC-LINK'] = "https://engage.247.ai/docportal/Content/"
	default['Self-Serve-BE']['CSS-APP-VCC-APP-URL'] = "https://engage.247.ai"
	default['Self-Serve-BE']['CSS-APP-SUPPORT-LINK']="https://247inc.atlassian.net/secure/RapidBoard.jspa?rapidView=1178&projectKey=SRE"
	default['Self-Serve-BE']['CSS-APP-TOOL-ROOT']="/self-serve"
	default['Self-Serve-BE']['CSS-APP-TOOL-NAME']="ASSIST"
	default['Self-Serve-BE']['CSS-APP-TOOL-TYPE']="internal"
	default['Self-Serve-BE']['CSS-APP-TOOL-TITLE']="Assist"
	default['Self-Serve-BE']['CSS-APP-OKTA-ENABLED']="true"
	default['Self-Serve-BE']['CSS-APP-ENV']="prod"
	default['Self-Serve-BE']['CSS-APP-SERVICE-BASE-URL']="https://engage.247.ai/self-serve"
	default['Self-Serve-BE']['CSS-APP-PARENT-BASE-URL'] = "https://engage.247.ai/home"
	default['Self-Serve-BE']['CSS-APP-COOKIES-SECURE-FLAG'] = "true"
	default['Self-Serve-BE']['CSS-APP-COOKIES-HTTPONLY-FLAG'] = "true"
	default['Self-Serve-BE']['CSS-APP-PROXY-ENABLE'] = "true"
	default['Self-Serve-BE']['CSS-APP-PROXY-HOST'] = "proxy-grp1.lb-priv.sv1.247-inc.net"
	default['Self-Serve-BE']['CSS-APP-PROXY-PORT'] = "3128"
	default['Self-Serve-BE']['CSS-APP-PROXY-PROTOCOL'] = "http"
	default['Self-Serve-BE']['CSS-APP-SSO-DISABLE'] = "false"
	default['Self-Serve-BE']['CSS-APP-THREAD-COUNT'] = "100"
	default['Self-Serve-BE']['CSS-APP-WORKFLOW-INSTANCE-TIMEOUT'] = "30"
	default['Self-Serve-BE']['CSS-APP-UMS-BASE-URL'] = "https://internal.api.247-inc.net"
	default['Self-Serve-BE']['location']      = "sv1"
	default['Self-Serve-BE']['webserver']     = "probe.private.sv1.tellme.com"
	default['Self-Serve-BE']['probeserver']   = "probe.private.sv1.tellme.com"
	default['Self-Serve-BE']['release']       = "statusd-20171023T2140"
	default['Self-Serve-BE']['mail_host']     = "mail.private.sv1.tellme.com"
	default['Self-Serve-BE']['ntp_server']    = "ntp01.private.sv1.tellme.com"
	default['Self-Serve-BE']['BULK-STORAGE'] = "gcp"
	default['Self-Serve-BE']['GCP-PROJECT-ID'] = "prd-chat-c8d5"
	default['Self-Serve-BE']['GCP-BUCKET-NAME'] = "prd-chat"
	default['Self-Serve-BE']['CREDENTIALS-FILE-PATH'] = "/var/tellme/css/conf/.gcp.json"

when 'CENTRAL-VA1-PROD'

	override['logstash']['hosts']= "logstash.logpool.lb-priv.va1.247-inc.net:5120"

	default['Self-Serve-BE']['WAR-REPO'] = "http://nexus.cicd.sv2.247-inc.net/nexus/repository/prod/com/tfsc/ilabs/self-service/promoted/self-service-promoted.jar"
	default['Self-Serve-BE']['spring.datasource.url'] = "jdbc:mysql://client-prov.db.lb-priv.va1.247-inc.net:3306/self_serve?useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false"
	default['Self-Serve-BE']['spring.datasource.username'] = "centraladmin"
	default['Self-Serve-BE']['spring.datasource.password'] = "central@247"
	default['Self-Serve-BE']['spring.datasource.driver-class-name']= "com.mysql.cj.jdbc.Driver"
	default['Self-Serve-BE']['spring.jpa.database-platform'] = "org.hibernate.dialect.MySQL5InnoDBDialect"
	default['Self-Serve-BE']['spring.jpa.show-sql'] = "false"
	default['Self-Serve-BE']['spring.jpa.hibernate.ddl-auto'] = "update"
	default['Self-Serve-BE']['server.servlet.application-display-name'] = "Self Service Application"
	default['Self-Serve-BE']['spring.application.name'] = "self-serve"
	default['Self-Serve-BE']['server.servlet.context-path'] = "/${spring.application.name}"
	default['Self-Serve-BE']['spring.jackson.serialization.write_dates_as_timestamp'] = "false"
	default['Self-Serve-BE']['server.port'] = "8090"

	default['Self-Serve-BE']['CSS-APP-OKTA-BASE-URL'] = "https://login.247.ai/"
	default['Self-Serve-BE']['CSS-APP-OKTA-AUTH-SERVICE-ID'] = "aus70mcr3rrgyTW3e2p7"
	default['Self-Serve-BE']['CSS-APP-CLIENT-ID'] = "0oa3fky9wv0Wy5acb2p7"
	default['Self-Serve-BE']['CSS-APP-CLIENT-SECRET'] = "Ks1vpMP8PKErREeRFRrlt_8sEyvkrAXishojiWEV"
	default['Self-Serve-BE']['CSS-APP-OKTA-CONNECTION-TIMEOUT'] = "1000"
	default['Self-Serve-BE']['CSS-APP-OKTA-CONNECTION-MULTIPLY'] = "1000"

	default['Self-Serve-BE']['CSS-APP-CONTENT-SERVER-BASE-URL'] = "https://engage.247.ai/"
	default['Self-Serve-BE']['CSS-APP-CONTENT-SERVER-CSS-CONTENT-BASE-PATH'] = "assist-console-ui/"
	default['Self-Serve-BE']['CSS-APP-DOC-LINK'] = "https://engage.247.ai/docportal/Content/"
	default['Self-Serve-BE']['CSS-APP-VCC-APP-URL'] = "https://engage.247.ai"
	default['Self-Serve-BE']['CSS-APP-SUPPORT-LINK']="https://247inc.atlassian.net/secure/RapidBoard.jspa?rapidView=1178&projectKey=SRE"
	default['Self-Serve-BE']['CSS-APP-TOOL-ROOT']="/self-serve"
	default['Self-Serve-BE']['CSS-APP-TOOL-NAME']="ASSIST"
	default['Self-Serve-BE']['CSS-APP-TOOL-TYPE']="internal"
	default['Self-Serve-BE']['CSS-APP-TOOL-TITLE']="Assist"
	default['Self-Serve-BE']['CSS-APP-OKTA-ENABLED']="true"
	default['Self-Serve-BE']['CSS-APP-ENV']="prod"
	default['Self-Serve-BE']['CSS-APP-SERVICE-BASE-URL']="https://engage.247.ai/self-serve"
	default['Self-Serve-BE']['CSS-APP-PARENT-BASE-URL'] = "https://engage.247.ai/home"
	default['Self-Serve-BE']['CSS-APP-COOKIES-SECURE-FLAG'] = "true"
	default['Self-Serve-BE']['CSS-APP-COOKIES-HTTPONLY-FLAG'] = "true"
	default['Self-Serve-BE']['CSS-APP-PROXY-ENABLE'] = "true"
	default['Self-Serve-BE']['CSS-APP-PROXY-HOST'] = "proxy-grp1.lb-priv.va1.247-inc.net"
	default['Self-Serve-BE']['CSS-APP-PROXY-PORT'] = "3128"
	default['Self-Serve-BE']['CSS-APP-PROXY-PROTOCOL'] = "http"
	default['Self-Serve-BE']['CSS-APP-SSO-DISABLE'] = "false"
	default['Self-Serve-BE']['CSS-APP-THREAD-COUNT'] = "100"
	default['Self-Serve-BE']['CSS-APP-WORKFLOW-INSTANCE-TIMEOUT'] = "30"
	default['Self-Serve-BE']['CSS-APP-UMS-BASE-URL'] = "https://internal.api.247-inc.net"
	default['Self-Serve-BE']['location']      = "va1"
	default['Self-Serve-BE']['webserver']     = "probe.private.va1.tellme.com"
	default['Self-Serve-BE']['probeserver']   = "probe.private.va1.tellme.com"
	default['Self-Serve-BE']['release']       = "statusd-20171023T2140"
	default['Self-Serve-BE']['mail_host']     = "mail.private.va1.tellme.com"
	default['Self-Serve-BE']['ntp_server']    = "ntp01.private.va1.tellme.com"
	default['Self-Serve-BE']['BULK-STORAGE'] = "gcp"
	default['Self-Serve-BE']['GCP-PROJECT-ID'] = "prd-chat-c8d5"
	default['Self-Serve-BE']['GCP-BUCKET-NAME'] = "prd-chat"
	default['Self-Serve-BE']['CREDENTIALS-FILE-PATH'] = "/var/tellme/css/conf/.gcp.json"

else
   puts "Chef Environment is --> #{node.chef_environment} -- I have no idea what to do with that!"
end
